import type { Metadata } from 'next'
import '../globals.css'
import { Header } from '@/components/Header'
import { Menu } from '@/components/Menu'
import { UserProvider } from '@/context/userContext'
import { i18nConfig } from '@/lib/i18n/i18nConfig'
import { dir } from 'i18next'
import { Plus_Jakarta_Sans } from 'next/font/google'

const plusJakarta = Plus_Jakarta_Sans({
	subsets: ['latin'],
	weight: ['400', '500', '700', '800'],
	variable: '--font-plus-jakarta',
})

export const metadata: Metadata = {
	title: 'Kanban Board',
	description: 'Generated by create next app',
}

export function generateStaticParams() {
	return i18nConfig.locales.map((locale) => ({ locale }))
}

export default async function KanbanBoardLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) {
	return (
		<html lang={locale} dir={dir(locale)}>
			<body className={`${plusJakarta.className}`}>
				<UserProvider>
					<div className='flex flex-col lg:flex-row'>
						<Menu locale={locale} />
						<div className='flex flex-col flex-1 items-center'>
							<Header locale={locale} />
							{children}
						</div>
					</div>
				</UserProvider>
			</body>
		</html>
	)
}
