import type { Metadata } from 'next'
import { Inter, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/context/authContext'
import { i18nConfig } from '@/lib/i18n/i18nConfig'
import { dir } from 'i18next'

const inter = Inter({ subsets: ['latin'] })
const plusJakarta = Plus_Jakarta_Sans({
	subsets: ['latin'],
	weight: ['400', '500', '700', '800'],
	variable: '--font-plus-jakarta',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export function generateStaticParams() {
	return i18nConfig.locales.map((locale) => ({ locale }))
}

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) {
	return (
		<html lang={locale} dir={dir(locale)}>
			<AuthProvider>
				<body className={`${inter.className} ${plusJakarta.variable}`}>
					{children}
				</body>
			</AuthProvider>
		</html>
	)
}
